repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies: [pydantic, pydantic-settings, loguru]
        args: [--strict, --ignore-missing-imports]
        files: ^src/

  - repo: local
    hooks:
      - id: generate-env-example
        name: Generate .env.example from .env
        entry: python scripts/generate_env_example.py
        language: python
        files: ^\.env$   
        pass_filenames: false  